create table album.PICTURES (
ID INT NOT NULL AUTO_INCREMENT,
PIC_OWNER VARCHAR(100) NOT NULL,
FILENAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(100),
PATH VARCHAR(100),
CREATED TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);

create table album.USERS (
LOGIN VARCHAR(100) NOT NULL,
PASS VARCHAR(100) NOT NULL,
ROLE VARCHAR(100) NOT NULL,
ACTIVE BOOLEAN NOT NULL DEFAULT 1,
PRIMARY KEY (LOGIN)
);
